### ISSUE TITLE
Thin line-weight/Poor figures - Adapted from other authors

### ISSUE THREAD

**Issue by karm-patel** [probml/pyprobml#1071]
Fig 4.33:
![image](https://user-images.githubusercontent.com/59387624/180839565-4fdc0de2-d333-4bc4-86c6-d104684f7b83.png)

9.11
![image](https://user-images.githubusercontent.com/59387624/180839654-d32767c9-7b00-43e1-ba92-530d63bcbfc5.png)

10.17(a)
![image](https://user-images.githubusercontent.com/59387624/180839910-18031fb6-d737-46ad-b661-aebed5b245ab.png)

11.6
![image](https://user-images.githubusercontent.com/59387624/180839994-a212658b-a240-409d-8e4f-ac69796ba30c.png)

12.7
![image](https://user-images.githubusercontent.com/59387624/180840159-06dc1f95-58de-4c4e-84cd-1fa17309b1a4.png)

12.22
![image](https://user-images.githubusercontent.com/59387624/180840099-3b8b26d4-9311-4d94-80e9-4813b816e9af.png)

18.28
![image](https://user-images.githubusercontent.com/59387624/180840244-ad1f099b-05b1-4647-b230-13b2a4706f72.png)

30.3
![image](https://user-images.githubusercontent.com/59387624/180840332-f05beb17-d537-4f6c-9cd7-0034762cacf1.png)

31.7
![image](https://user-images.githubusercontent.com/59387624/180840430-2a6c5bff-b1d0-4434-913d-1edee483245a.png)

35.4
![image](https://user-images.githubusercontent.com/59387624/180840633-9b40c022-9f05-46a1-90d1-3f3840f35fbd.png)

**Comment by murphyk** [comment]
Comments
- 4.33. I have asked Jay Chen for a new version although IMHO it is fine as is.
- 9.11. This figure was used in book 0 p892 and printed ok
- 10.17 . I have removed this section.
- 11.6. I have asked Nando for the original (unlikely to get it in time). 
- 12.7. Figure is removed.
- 12.22. I have made these figures bigger which helps a lot. Also I have the matlab source code and can regenerate, although the current pdf's seem sharp to me.
- 18.28. I have removed this figure and replace it with the one attached.
- 30.3. This figure was used in book 0 p976 and printed fine.
- 31.7. This will be removed. 
- 35.4. I have made this bigger, hopefully it will help.  (Could be redrawn...)

New NN GP kernel figure instead of 18.28. I have asked the author for the source.

<img width="464" alt="Screen Shot 2022-07-26 at 3 43 36 PM" src="https://user-images.githubusercontent.com/4632336/181128962-b158cbb6-de7b-46db-b989-aad7fec0caab.png">
