### ISSUE TITLE
Convert logregLaplaceGirolamiDemo to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#201]
This is figure number 10.15 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/logregLaplaceGirolamiDemo.m)

**Comment by shivaditya-meduri** [comment]
Since the data is generated randomly, the graphs might not look similar to the ones in the book.
I've used mathematical concepts behind the graphs to create this python file so I feel these graphs are relevant,
Please let me know if you feel I haven't used the maths correctly and I will incorporate your suggestions into the code,
Have a good day!
