### ISSUE TITLE
Convert pcaEmStepByStep to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#229]
This is figure number 20.10 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/pcaEmStepByStep.m)

**Comment by ashishpapanai** [comment]
May I work on this @mjsML?

**Comment by mjsML** [comment]
Please go ahead :) ... the comment is a mere courtesy others to let them know someone is working on it instead of searching the pending pulls 🙂

**Comment by ashishpapanai** [comment]
Hello @mjsML,
I have a query in line number 8 and 21 of  gaussPlot2d.m [link](https://github.com/probml/pmtk3/blob/master/matlabTools/graphics/gaussPlot2d.m)
What is the specific function of process_option? 

And, Is this the correct file to refer for gaussPlot2d function mentioned in line 42 [here](https://github.com/probml/pmtk3/blob/master/demos/pcaEmStepByStep.m)

**Comment by mjsML** [comment]
@murphyk would you care to chime in here?

**Comment by murphyk** [comment]
Don't get too hung up on  how each line of Matlab works. Instead, look at the figure, read the text (and equations!) of the corresponding section of the book, and think for yourself how you would make that figure in Python. You can use the Matlab source as a 'hint'. Then start coding :)

(This particular example was a homework exercise in my class when I taught at UBC. The [code in pmtk3](https://github.com/probml/pmtk3/blob/master/demos/pcaEmStepByStep.m) was written by Cody Severinski.)

The core code implements the equations in sec 20.2.3.2 ("EM for (P)PCA"). In particular, the unnumbered equations labeled "E step" and "M step".

The [gaussPlot2d.m](https://github.com/probml/pmtk3/blob/master/matlabTools/graphics/gaussPlot2d.m) function just plots the Gaussian 95% confidence ellipse.
For a Python version you can use, look at [this script](https://github.com/probml/pyprobml/blob/master/scripts/gauss_plot_2d.py).

The [process_options.m](https://github.com/probml/pmtk3/blob/master/matlabTools/util/process_options.m) function is a poor-man's argument parser that I wrote 2 decades ago (since Matlab does not support keyword arguments, unlike Python).

PS. It seems that @gerdm  has implemented some closely related code - See [his ppca.py](https://github.com/gerdm/prml/blob/master/chapter12/ppca.py) script and [his ppca notebook](https://github.com/gerdm/prml/blob/master/chapter12/probabilistic-pca.ipynb). If you copy his code and modify it, please be sure to credit him!

**Comment by murphyk** [comment]
fixed in https://github.com/probml/pyprobml/blob/master/scripts/pcaEmStepByStep.py
