### ISSUE TITLE
Convert mixPpcaDemoNetlab to python

### ISSUE THREAD

**Issue by mjsML** [probml/pyprobml#230]
This is figure number 20.12 in the book. its matlab code is [here](https://github.com/probml/pmtk3/blob/master/demos/mixPpcaDemoNetlab.m)

**Comment by ashishpapanai** [comment]
Hello @mjsML, I would like to work on this issue.

**Comment by mjsML** [comment]
> Hello @mjsML, I would like to work on this issue. 

Please go ahead, you can look at #99 for instructions.
When you submit a pull request, kindly mention the issue number and ask for a review from @murphyk and myself.
Thanks!

**Comment by ashishpapanai** [comment]
I have a few queries @mjsML,
 ```
if ~exist('gmm')
   error('must install netlab from http://www.ncrg.aston.ac.uk/netlab/index.php')
```
 **1.** In these lines are we checking for a variable 'gmm' of a file. Because I tried to check for a local or a global variable with this name in python by running: 
```
 if not ('gmm' in locals()):
        raise Exception("must install netlab from http://www.ncrg.aston.ac.uk/netlab/index.php")
```
I got the exception which I have raised in the second line, _**and the suggested website is down.**_ 

**2.**  Is gmmint a specific function of MATLAB or is it a function defined in any other module in the scripts folder?
` mix = gmminit(mix, data, options);`

**3.**  Is gmem a specific function of MATLAB or is it a function defined in any other module in the scripts folder?
`[mix, options, errlog] = gmmem(mix, data, options);`

**Comment by mjsML** [comment]
@murphyk also here 🙂

**Comment by murphyk** [comment]
All the netlab code is [here](https://www.mathworks.com/matlabcentral/fileexchange/2654-netlab).
The command "if ~exist('gmm')..." just checks if the gmm() function is on Matlab's global path (since Matlab does not have proper package management system...)

But rather than trying to get the old matlab code running, you could just try to reproduce the figure itself (or something similar) using a python implementation of the algorithm. I don't think it's in sklearn, but a quick google search for "mixtures of PPCA" reveals these implementations (WTFPL license):
- https://github.com/michelbl/MPPCA
- https://github.com/aghriss/MPPCA

I don't know if either of those work. If not, you will have to implement it yourself - it's a good exercise (but challenging!). I briefly describe the method in the book, but the details are in [Tipping's original paper](http://www.miketipping.com/papers/met-mppca.pdf). 

If you want to be fancy, you could try adding a covariance_type='low-rank' option to the [sklearn.mixture.gaussianMixture](https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html#sklearn.mixture.GaussianMixture) class.

(See also the [Pomegranate library](https://pomegranate.readthedocs.io/en/latest/GeneralMixtureModel.html)
and the [Pyro libary](https://pyro.ai/examples/gmm.html).)

**Comment by vishvjoshi** [comment]
Hello @mjsML, I would like to work on this issue.
