### ISSUE TITLE
convert LeNet1989 from Torch to JAX

### ISSUE THREAD

**Issue by murphyk** [probml/pyprobml#698]
In [this excelllent blog post](https://karpathy.github.io/2022/03/14/lecun1989/), Andrej Karpathy reimplements the original 1989 LeNet paper using modern methods. Convert the code in [his repo](https://github.com/karpathy/lecun1989-repro) to JAX/Flax.

**Comment by peterchang0414** [comment]
I'd like to take this up!

**Comment by susnato** [comment]
Hi, @murphyk do we need to create an notebook for this issue or do we only need to create a script ?

**Comment by murphyk** [comment]
@susnato I think a notebook is better (easier to use).

**Comment by nalzok** [comment]
I will work on this one as well. This sounds fun, and it would be interesting to compare different people's implementation against each other.

**Comment by peterchang0414** [comment]
My Colab notebook for this issue: https://colab.research.google.com/github/peterchang0414/lecun1989-flax/blob/main/lecun_scratch.ipynb

Should I commit the notebook file to pyprobml/notebooks?

**Comment by nalzok** [comment]
It looks like I'm a bit late to the party, but my work is almost done (there is still some documentation to be added, but I expect to open a pull request in 24 hours). Here is the notebook link

https://colab.research.google.com/drive/1N5qvJfmJnHgmfSdw8frU5C9J7gS_NgKX?usp=sharing

The result I got is

```
train epoch: 23, loss: 0.0041, accuracy: 99.38
test epoch: 23, loss: 0.04, accuracy: 93.47
```

Since you asked for a notebook, I assume you would like to optimize for readability. As a result, I based my work on Flax's official [Annotated MNIST](https://flax.readthedocs.io/en/latest/notebooks/annotated_mnist.html) notebook, which includes a lot of comments and is very comprehensive. It turns out only a small modification is required to implement the CNN appeared in LeCun et al. 1989.

I just took a brief look at the notebook provided by @peterchang0414. Apart from different coding styles, there are not many differences between our implementations, despite we worked independently.

I have not added the modern adjustments yet to avoid bloating the notebook, but I can include some if that's desirable. In fact, I have experimented with making all units in the convolutional layers share their bias in addition to the weights, and using minibatch instead of SGD. Both adjustments don't seem to have a huge impact, though.

**NOTE:** I have not finished yet, but I decided to share a preview version with you so that you can provide some feedback. I don't want to spend time working on some aspects you don't care about.

**Comment by nalzok** [comment]
As a note for posterity, we don't need to resize the MNIST dataset as Andrej Karpathy did. The original dataset used by LeCun can be accessed [at this URL](https://hastie.su.domains/ElemStatLearn/data.html). I have included the readme below.

```
Normalized handwritten digits, automatically
scanned from envelopes by the U.S. Postal Service. The original
scanned digits are binary and of different sizes and orientations; the
images  here have been deslanted and size normalized, resulting
in 16 x 16 grayscale images (Le Cun et al., 1990).

The data are in two gzipped files, and each line consists of the digit
id (0-9) followed by the 256 grayscale values.

There are 7291 training observations and 2007 test observations,
distributed as follows:
         0    1   2   3   4   5   6   7   8   9 Total
Train 1194 1005 731 658 652 556 664 645 542 644 7291
 Test  359  264 198 166 200 160 170 147 166 177 2007

or as proportions:
         0    1   2    3    4    5    6    7    8    9 
Train 0.16 0.14 0.1 0.09 0.09 0.08 0.09 0.09 0.07 0.09
 Test 0.18 0.13 0.1 0.08 0.10 0.08 0.08 0.07 0.08 0.09


Alternatively, the training data are available as separate files per
digit (and hence without the digit identifier in each row)

The test set is notoriously "difficult", and a 2.5% error rate is
excellent. These data were kindly made available by the neural network
group at AT&T research labs (thanks to Yann Le Cunn).
```
