### ISSUE TITLE
Use Python 3.9.12 consistently?

### ISSUE THREAD

**Issue by patel-zeel** [probml/pyprobml#762]
## Problem
Contributors might be using different Python versions and that may fail some of the notebooks. Thus, it is recommended to use Python 3.9.12 which is used by the docker container we use in our workflow.

## Solution
Recommend to use Python 3.9.12 in [the instructions](https://github.com/probml/pyprobml/blob/master/notebooks/README.md).

**Comment by murphyk** [comment]
FYI Colab uses python 3.7.13, at least my version (Colab Pro +)

**Comment by patel-zeel** [comment]
@murphyk I checked and found that basic colab also uses 3.7.13. Given that most users will use Google colab, shall we pin 3.7.13? and in the future be in line with colab Python version?

**Comment by nalzok** [comment]
Now that we are pinning the default Python version, shouldn't we also pin library versions, which typically move faster than the interpreter? In fact, Colab updates its packages [very regularly](https://colab.research.google.com/notebooks/relnotes.ipynb). For example, jax v0.3.4 was released on 2022/03/18, and Colab uses it on 2022/3/25, just one week later.

Alternatively, we can `pip install --upgrade` all packages to test against the latest versions. I actually think it is a better idea to keep our code up-to-date instead of living with some old version since newer packages are naturally superior.

By the way, Colab switched their default Python version from 3.6 to 3.7 [on 2021/02/25](https://twitter.com/googlecolab/status/1365062244225060865?lang=en), so I suspect the upgrade from 3.7 to 3.8 won't be distant.

**Comment by patel-zeel** [comment]
We will reopen for further discussion if needed.
